name: Numpad

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Numpad
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run:  bash ipabuild.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Numpad - Extract it
          path: |
            /Users/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/build/Numpad.ipa